dist: xenial
sudo: false
language: python
python: "3.7.1"

install:
  - pip3 install --upgrade -r requirements.txt

script:
  - flake8
  - python3 -m pytest test

after_success:
  - bash test/deploy.sh
