dist: xenial
sudo: false
language: python
python: "3.7.1"

before_install:
  - rm -rf $HOME/.cache/pip/http
  - rm -rf $HOME/.cache/pip/log

install:
  - pip3 install --upgrade -r requirements.txt

script:
  - flake8 --config=tox_test.ini test
  - flake8
  - python3 -m pytest test

after_success:
  - bash test/deploy.sh

cache:
  directories:
    - $HOME/virtualenv/python3.7.*
    - $HOME/.cache/pip

before_cache:
  - rm -rf $HOME/.cache/pip/http
  - rm -rf $HOME/.cache/pip/log
